version: '3.8'

services:
  websocket-server:
    image: hoanghy/virtual-human-tracking
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
